name: adapt_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - xarray
  - pandas
  - scipy
  - arm_pyart
  - opencv
  - scikit-image
  - matplotlib
  - cartopy>=0.21
  - netCDF4
  - tqdm
  - h5py
  - proj
  - hdf5
  - libnetcdf
  - pip
  - pytest>=7.0
  - pytest-cov
  - sphinx>=4.0
  - sphinx-rtd-theme>=1.0
  - pip:
      - pydantic>=2.0
      - nexradaws
      - contextily
      - pyproj
      - pyarrow
      - sphinx-autodoc-typehints
      - -e .[dev]

