name: adapt_env
channels:
  - conda-forge
dependencies:
  - python=3.11  # or 3.12, overridden by CI matrix
  - numpy
  - xarray
  - pandas
  - arm_pyart
  - opencv
  - scikit-image
  - matplotlib
  - cartopy
  - netCDF4
  - tqdm
  - h5py
  - proj
  - hdf5
  - libnetcdf
  - pip
  - pytest
  - pytest-cov
  - pip:
      - nexradaws
      - contextily
      - pyproj
      - -e .[dev]
